### ISSUE TITLE
For easier renaming, merge everything and recreate branches?

### ISSUE THREAD

**Issue by zgoethel12** [team-jgloom/jgloom#10]
1. Merge all of the branches
2. Create the rename branch and refactor everything
3. Merge that branch
4. Recreate dev and feat/featname branches

(Master and dev are so out of date, anyway)

**Comment by ecumene-software** [comment]
1. Make a commit to a branch of master
2. Merge that branch with all the other branches 
3. Delete branch

;)

**Comment by ecumene-software** [comment]
I was just doing this right now actually

**Comment by zgoethel12** [comment]
When are we going to merge with master, it doesn't have anything resembling the current development version.

**Comment by ecumene-software** [comment]
Once the globject wrapping is done, then we make file loaders / utilites to manipulate all the globjects.

**Comment by zgoethel12** [comment]
Sounds good.  I'll just close this issue.

**Comment by ecumene-software** [comment]
Imma go with your method actually... I moved `JOOGLException` in the `feat/globjects` so it's unsynced with `master`... I'll see if I can merge all the branches now!
