### ISSUE TITLE
Separating utilities from GL Objects.

### ISSUE THREAD

**Issue by ecumene-software** [team-jgloom/jgloom#11]
The design of the library is supposed to draw a line between API calls and the OpenGL objects. For example the GLFW windows:

````
joogl.gl.GLFWWindow          - The object (getWindow() : int)
joogl.gl.GLFWWindowContainer - Object specific API Calls
joogl.gl.GLFWWindows         - Non object specific API calls (GLFW context stuff)
````
What I'm proposing is:
````
joogl.gl.GLFWWindow          - The object (getWindow() : int)
````
````
joogl.commons.GLFWWindowContainer - Object specific API Calls
joogl.commons.GLFWWindows         - Non object specific API calls (GLFW context stuff)
````
It's kinda essential we have this differentiation between JOOGL/JGLOOm (I'll change the package name later) so people know the `joogl.gl.*` is strictly for OpenGL objects and everything else is just 'extra'.

**Comment by zgoethel12** [comment]
Sure, sounds good.
