### ISSUE TITLE
Redesigned icon (concept drawing)

### ISSUE THREAD

**Issue by zgoethel12** [team-jgloom/jgloom#12]
I hopped into Inkscape and threw this together.  I was wondering if you like it.
It is not a final design, and can be tweaked, perhaps starting with removing the black border and maybe even the clouds.

*[Removed]*

On the organization page:

*[Removed]*

**Edit:** Removed border and clouds just looks like this

*[Removed]*

**Comment by ecumene-software** [comment]
It's too large vertically, and it doesn't look very iconic. Check out this article: 
http://ideas.overnightprints.com/the-five-essential-elements-of-effective-logo-design/

**Comment by zgoethel12** [comment]
I said it needed tweaking

**Comment by zgoethel12** [comment]
You should look at my JStitch icon on 'feat/server' on GitHub or Bitbucket

**Comment by ecumene-software** [comment]
![imgsafe](https://i.imgsafe.org/fa48aa1.png)

How's this?

**Comment by zgoethel12** [comment]
It's nice, and it gives us room under the m for a 2 (JGLOOm 2.0)

**Comment by ecumene-software** [comment]
I'm debating whether to have it as subscript or superscript... What do you think?

**Comment by zgoethel12** [comment]
Superscript, definitely

**Comment by ecumene-software** [comment]
Okay I'll throw together a commit for the icon + logo and a second one for the package move I proposed earlier.
