### ISSUE TITLE
Starting a wiki to aid developers

### ISSUE THREAD

**Issue by zgoethel12** [team-jgloom/jgloom#13]
Once our library is to the right point, we should open a wiki.
I would design the pages as so:
* Setting up contexts
* Opening a window
* Compiling shaders
* Creating programs
* Rendering a triangle

**Comment by ecumene-software** [comment]
I love wikis, I hate making them for new projects... Honestly I think it'd be hard to write at this stage, it's on the back burner though!

**Comment by ecumene-software** [comment]
I plan to start the wiki just before the release date on June 30th, the markdown should be compatible with some kind of MD to HTML reader, because the github pages website is just around the corner also. `jgloom.org` seems to be very cheap and I'll plan to buy it in the future.

**Comment by ecumene-software** [comment]
I wrote two pages for the wiki, they're up now.
