### ISSUE TITLE
Create GLFrameBuffer wrappers

### ISSUE THREAD

**Issue by ecumene-software** [team-jgloom/jgloom#17]
The Framebuffer wrapper should include all the functions listed here: https://www.opengl.org/wiki/Framebuffer_Object

**Comment by zgoethel12** [comment]
If you want to work on the functionality, you should self-assign to avoid conflicts.

**Comment by zgoethel12** [comment]
When binding a framebuffer (or completing most operations), it takes an argument for target.  Should I default it to GL_FRAMEBUFFER, or allow user input (somewhat ruining the whole "high level" thing by requiring constant use of target names)

**Comment by zgoethel12** [comment]
I'll just write things with target variables.

**Comment by ecumene-software** [comment]
Targets are hard to make high-level and it's tempting to track them with an integer, but you're still losing some functionality (like binding a 2D texture to a cubemap sampler) if you do. So it's better to sacrifice form for function on that stuff.

**Comment by zgoethel12** [comment]
You should take a look at the current status.  There is likely something you won't like.  Once it is more complete, I'll leave the documentation to you.  GLRenderBuffer is currently empty.

**Comment by ecumene-software** [comment]
I'll write a few improvements once I've finished the GLBuffer wrapper
