### ISSUE TITLE
Move all "GL[object]s" functions to "GL[object]"

### ISSUE THREAD

**Issue by ecumene-software** [team-jgloom/jgloom#19]
Just learned today you can define static functions inside of interfaces, it's pretty groovy.

We should put all our functions inside of "GL[object]s" into "GL[object]", this doesn't necessarily mean we really have to move everything back to the gl package, only the static methods.

Technically an enhancement, more of a facepalm on my part. Let's have a vote! (I say we do it so that's already 50% of our Parliament)

**Comment by zgoethel12** [comment]
If it is compliant with Java 6, I'm in.
