### ISSUE TITLE
Reduce amount of casts or shorten casts?

### ISSUE THREAD

**Issue by zgoethel12** [team-jgloom/jgloom#21]
This library currently is built in this fashion: a GL object is wrapped by an interface by an implementing class.  Our design makes people feel like they have to create the interface versions of the wrappers, then cast it to the implementation whenever they want to make a call.  This is an inefficient way to code, and I have two solutions.

1. Add method declarations to the interfaces.  Users can still create their own wrappers, which should at least implement the method we implemented.
2. Rename interfaces to 'IGL[Object]' and classes to 'GL[Object], which reduces the length of the casts or makes it seem okay to define variables of the container variety.

We could do one, both, our neither.  I like the idea of adding definitions to the interfaces to promote functional user-made wrappers.

**Comment by zgoethel12** [comment]
Reading some Slick2D docs on the bus showed me that they used a similar design to option one, with interface 'Texture' (with all required methods) and container 'TextureImpl' which implements the interface

**Comment by ecumene-software** [comment]
Its bad practice to use I in Interfaces. People generally use AbstractX to implement interfaces now... which is a bit shorter than Container. 

As for casting... You wouldn't have to cast anything if the primary type of the instance was the container and not the interface ;)

Although I do like the idea of Abstract classes, it implies youre just implementing the interfaces methods. But we can change it.

**Comment by ecumene-software** [comment]
Also adding all those container methods to the objects would be pointless, the interfaces were made to represent an integer as an opengl object in Java. Not the functions, the containers do that

**Comment by zgoethel12** [comment]
Well, what I was thinking was we could do something like:

    public interface GLObject {
        public void doSomething();
    }

    public class GLObjectContainer implements GLOBject
        @Override
        public void doSomething() {
            
        }
    }

So you can call `doSomething` on an interface without casting it to `GLObjectContainer`, since all `GLObject`s should implement the method `doSomething`.

**Comment by ecumene-software** [comment]
Here's how you can avoid your casting thing:
````
GLObject object = new GLObjectContainer(GLObject.create());
((GLObjectContainer) object).doSomething();
````

Instead, do this:
````
GLObjectContainer object = new GLObjectContainer (GlObject.create());
object.doSomething();
````

**Comment by zgoethel12** [comment]
I have been, but I don't like defining so many objects with the postfix "Container"

**Comment by ecumene-software** [comment]
What looks better?
````
GLObjectContainer 
AbstractGLObject
GlObjectImpl
````

**Comment by ecumene-software** [comment]
bump

**Comment by zgoethel12** [comment]
I guess container naming is fine

**Comment by ecumene-software** [comment]
Ah, okay. 50% + 50% makes a 100% majority!
