### ISSUE TITLE
Needs more tests

### ISSUE THREAD

**Issue by ecumene-software** [team-jgloom/jgloom#24]
We need to very thoroughly test these objects / functions:
- Offscreen famebuffers
- Texture binding and uploading simple data
- Renderbuffer manipulation
- GLBuffer tests (by uploading geometry?)

We should be able to do this relatively soon. It's the main focus of the project now to test as many features as possible, the more sensitive JUnit is to changes the better!

**Comment by ecumene-software** [comment]
Once these tests are done, we can start a new branch for loading and file formats and finally make this into a useful library

**Comment by zgoethel12** [comment]
Testing commits directly to dev, or to something like feat/forests?

**Comment by ecumene-software** [comment]
Straight to dev, the tests should test the features I listed above
