### ISSUE TITLE
Start continuous integration via Travis CI

### ISSUE THREAD

**Issue by zgoethel12** [team-jgloom/jgloom#25]
I would like to start a Travis page for our project.  I know how, and can do it myself.

**Comment by zgoethel12** [comment]
I sent an access request for Travis; accept it and I will move forward, comment "no" and I'll stop.

**Comment by ecumene-software** [comment]
What's travis? It looks like remote testing

**Comment by zgoethel12** [comment]
Yup, then we can add the build status icon to our readme.

**Comment by ecumene-software** [comment]
Oh, thats cool! Sure

**Comment by zgoethel12** [comment]
Alright, just make sure you accept and I'll get started.

**Comment by zgoethel12** [comment]
One thing: with Travis CI, you have to wait before merging your pull requests so it can build them.  Otherwise it errors the build.

**Comment by ecumene-software** [comment]
Okay, that's no biggie.

**Comment by zgoethel12** [comment]
You need to go accept the Travis access request I sent.  Check your email.

**Comment by zgoethel12** [comment]
I'm holding back my commits so that I can run a test build once Travis CI is accepted.  You need to go to your email and accept the access request I sent.

**Comment by zgoethel12** [comment]
It seems that Travis has some issues with the 3.0.0a, I'm updating the library to 3.0.0-SNAPSHOT which is a major change so try not to commit.

**Comment by zgoethel12** [comment]
I'm having a lot of problems with the native libraries and them not loading.  I'll keep working on it.

**Comment by ecumene-software** [comment]
Hey, sorry I didn't accept it! I'll do that now. The native libraries probably won't work on some build server that doesn't have those shared libraries installed. I'll see if I can add them as a dependency to gradle somehow
