### ISSUE TITLE
Remove unit testing

### ISSUE THREAD

**Issue by ecumene-software** [team-jgloom/jgloom#27]
The multi-threading is breaking a lot of my OpenGL code, and doing anything other than creating windows in GLFW (like input) in another thread is unheard of and unsupported.

There's no point in running unit tests, and it'd be way better to just have main classes to run.

(And yes, I'm calling junit a bug)

**Comment by ecumene-software** [comment]
We remove the whole continuous integration technique... But we can use it in `JGLOOm-io`, where it only involves file loading.

**Comment by zgoethel12** [comment]
I believe I've already abandoned CI.  I haven't noticed multi-threading issues, but okay.

**Comment by ecumene-software** [comment]
Second thought I may be able to modify the gradle script to still build the project if the test doesn't have "GL" in it's name.

**Comment by zgoethel12** [comment]
By the way, I'm developing a new CI software from the ground up called JTrial CI.  I'm designing it so that graphical applications can run with full contexts.  I guess I'll see how well that goes.  [Team JTrial](https://github.com/team-jtrial) [JTrial CI](https://github.com/team-jtrial/jtrial-ci)
