### ISSUE TITLE
Container Checklist

### ISSUE THREAD

**Issue by ecumene-software** [team-jgloom/jgloom#33]
Here's a list of containers we need to implement with the new abstract system
- [x] GLFWWindows
- [x] GLFWMonitors
- [x] GLBuffers
- [x] GLFrameBuffers
- [x] GLRenderBuffers
- [x] GLTextures
- [x] GLVertexArray

**Comment by ecumene-software** [comment]
@zgoethel12 Should I rename FrameBuffer to Framebuffer, I can't find any official docs that read it different...

**Comment by zgoethel12** [comment]
I always name it `Framebuffer`, since it's always written as framebuffer (not frame buffer) in the docs

**Comment by zgoethel12** [comment]
Plus Renderbuffer and etc.

**Comment by ecumene-software** [comment]
Okay, I changed it, thanks!
