### ISSUE TITLE
Interfaces for groups of OpenGL functions

### ISSUE THREAD

**Issue by ecumene-software** [team-jgloom/jgloom#34]
The library should have a package for every OpenGL object containing groups of functions for manipulating it. This way you can pick and choose which containers to use when drawing or uploading formats.
```
jgloom.functions.buffer
jgloom.functions.framebuffer
jgloom.functions.texture
...
```
Example
----------
Then inside of each you'd have
```
jgloom.functions.buffer.GLFBuffer        // Basic bind, delete, generate
jgloom.functions.buffer.GLFBufferStorage // Extends GLBuffer
jgloom.functions.buffer.GLFBufferData    // Extends GLBuffer
```
```
// LWJGL Supports all of those, so ...
class LWJGLBufferContainer implements GLFBuffer, GLFBufferData, GLFBufferStorage ...
// For example if WebGL didn't ...
class WebGLBufferContainer implements GLFBuffer, GLFBufferData ...
```

By doing this we can have a method inside a file loader like this:
```
void uploadData(GLFBufferData uploadMethod);
```

Since the LWJGL containers support glBufferData we implement that interface (GLFBufferData) into the containers, allowing for the container to be used in uploadData. If a container doesn't support it then they have to use a method that does.

This is a way to breach the language barrier in different graphics libraries, which makes the file loading for a wide range of graphics libraries possible. 

Here's a checklist of Objects to cover. ( In no order )
 - [x] Buffers
 - [x] Framebuffers
 - [x] Renderbuffers
 - [x] Textures
 - [x] Vertex Arrays
 - [x] Shaders
 - [x] Shader Programs

**Comment by zgoethel12** [comment]
I fully support moving towards static methods that pass a certain implementation rather than adding implementation-specific to the implementation and having to cast.  (`StaticMethods.doStuff(ObjImpl obj)` rather than `((ObjImpl) obj).doStuff()`)

**Comment by ecumene-software** [comment]
This breaks functionality for non-statically contexted libraries like JOGL though, which I wanted to support. Also it's not very object oriented ;)

**Comment by zgoethel12** [comment]
Maybe you should elaborate on how your idea is different.

**Comment by ecumene-software** [comment]
JOGL requires a context (an object in Java) to call any OpenGL methods, while LWJGL is static. So a static class wouldn't work. Unless we implement some sort of context tracking method which is out of the scope of this library because the user would have to keep track of which context is being used in the static class.

This would also mean we sacrifice child classes of containers that react to calls on object-specific basis. Why not use static classes: Two OGL object containers couldn't operate differently when put into a method, which this whole feature is about. Also I don't think the interfaces should be used as the type of any object anyway, if you're operating on an object use a container as the type.

**Comment by zgoethel12** [comment]
I like the idea of separating methods based on groups supported by different APIs.

**Comment by ecumene-software** [comment]
Yeah! That's what I'm preachin'! There could be one library for MD5, OBJ, FBX and support all the popular platforms + libraries including backwards compatibility with old OpenGL versions.

This way nobody has an excuse to spend weeks writing their own loaders, or choosing from the bazaar of bloated engines out there.

**Comment by gouessej** [comment]
You can use the static method GLContext.getCurrentGL(). I advise you to look how those things are managed in existing scenegraph APIs.

**Comment by zgoethel12** [comment]
GLContext is deprecated, isn't it?  The version is LWJGL we are using does not have the class.

**Comment by gouessej** [comment]
@zgoethel12 I was talking about JOGL, this class exists:
http://jogamp.org/deployment/jogamp-next/javadoc/jogl/javadoc/com/jogamp/opengl/GLContext.html

It contradicts what @ecumene-software wrote, it uses an object-oriented API but there are some static helpers. Of course, if you call this method when the OpenGL context isn't current, it won't work.

**Comment by ecumene-software** [comment]
Added a checklist in OP

**Comment by zgoethel12** [comment]
Are display lists something we are wanting to support?

**Comment by ecumene-software** [comment]
I'll open an issue, I forgot about them.

**Comment by ecumene-software** [comment]
I don't think we should actually, there's no OpenGL doc on it. https://www.opengl.org/wiki_132/index.php?search=Display+lists&title=Special%3ASearch&go=Go

**Comment by ecumene-software** [comment]
All done!
