### ISSUE TITLE
Adding GL constants to their corresponding interfaces

### ISSUE THREAD

**Issue by zgoethel12** [team-jgloom/jgloom#35]
An issue presented with something like the texture system is the `target` variable (other classes have this too).  This requires whoever is using the library to use `GL11.GL_TEXTURE_2D` whenever they want to bind a texture as 2D.  My idea regarding this would be to add constants to the interfaces.

    public static final int TEXTURE_2D = GL11.GL_TEXTURE_2D;
    // Etc.

This way, the user could just use `GLTexture.TEXTURE_2D` and not have to worry about which GL version contains that constant (can be included in javadoc of said constant) or about importing both `GL11` and `GLTexture` since it's supposed to be a complete wrapper.

Ecumene edit:
Checklist for the issue tracker!

- [ ] EnumUtil interface (core jgloom-io `#setEnums(Class clazz)`)
- [ ] LWJGLEnums 
- [ ] TextureLoader Impl

**Comment by ecumene-software** [comment]
I planned to remove all the LWJGL code from the `jgloom.gl` package, so this won't work. I want to remove LWJGL as a dependency for the core library. There may even be a separate repo called jgloom-lwjgl

**Comment by zgoethel12** [comment]
You should let me know how the new layout will be, and check out my comments on jgloom-io

**Comment by ecumene-software** [comment]
Giving credit where it's due, I'll reopen this one and copy my ideas from the old.

**Comment by ecumene-software** [comment]
Copied from #45 

There's a pretty big issue I forgot about in the JGLOOm-IO project, how do we cross the barrier between libraries enumorator wise, I was thinking about something like this (and it's all I have to far + it's implemented right now)
Take for example the TextureLoader
```
public class TextureLoader {

    public static int E_11RGBA8; // E stands out when looking for fields in reflection
    public static int E_11RGB8; // 11 is the version class it comes from
    public static int E_11RGBA;
    public static int E_11RGB;
    public static int E_11FLOAT;
    public static int E_11TEXTURE_2D;

...
// In use:
texture.image2D(target, 0, callback.hasAlpha ? RGBA8 : RGB8, callback.width, callback.height, 0, callback.hasAlpha ? RGBA : RGB, FLOAT, data);
```

Then we have a class per-library like this:
```
public class LWJGLEnums {

...

public void setEnums(Class clazz){
    // Uses reflection to find enums with E_[version][enum] and sets them to the correct number
    // Using -1 to describe unusable enums between libraries (we can check between the versions)
```

This allows us to support specific enums from any library while also changing them dynamically per library also!

**Comment by ecumene-software** [comment]
So cool how you can necro threads like that :+1: 

Adding on my above model, here's a checklist:
- [ ] EnumUtil interface (core jgloom-io `#setEnums(Class clazz)`)
- [ ] LWJGLEnums 
- [ ] TextureLoader Impl

**Comment by zgoethel12** [comment]
Putting the enums into the loader won't work, unless you plan on implementing a loader for each API.  I'm going to move them to the containers.
