### ISSUE TITLE
Kotlin?

### ISSUE THREAD

**Issue by ecumene-software** [team-jgloom/jgloom#36]
Should we migrate to kotlin? I'm bored of Java, and Kotlin seems like a good language for this type of library (very simple object-oriented stuffs), plus it has lambdas also!

This thread will be dedicated entirely to the analysis of JGLOOm + Kotlin: Do's and Dont's meanwhile I'll keep working on the library.

**Comment by zgoethel12** [comment]
How about we open a repo `jgloom-kotlin` or `kgloom` or something, and you can manage it and I'll mostly stay with Java and the IO repo?  I don't know much about the language, its platform support, or GL integration.

**Comment by zgoethel12** [comment]
Does Kotlin compile into JARs as well?  From what I've seen, it's a shell for Java.

**Comment by ecumene-software** [comment]
Typically you wouldn't differentiate Java and Kotlin, their only difference is source, they both compile to bc, but one I assume is easier to automate the code writing process. I haven't touched it though, its completely operateable with Java code and libraries also.

**Comment by ecumene-software** [comment]
I'm going to make another branch, I'll probably commit some basic code to set up the library and all
