### ISSUE TITLE
JGLOOm and JGLOOm IO merge

### ISSUE THREAD

**Issue by ecumene-software** [team-jgloom/jgloom#37]
Using gradle, we can include the two projects to build at once. Which gives some flexibility to how we develop it, with dependencies and all. I'll be merging them today, which will change the directory structure:

```
[root]/build.gradle
[root]/settings.gradle
// The core project goes to
[root]/jgloom/build.gradle
[root]/jgloom/src/
// The JGLOOm IO project goes to
[root]/jgloom-io/build.gradle
[root]/jgloom-io/src/
```

Building the gradle file in the root directory builds the two, and tests at the same time.

**Comment by zgoethel12** [comment]
I'm on vacation with my family, but I'll do this soon!  How do you want them merged, with jgloom-io as a Gradle module but still a separate repo?

**Comment by ecumene-software** [comment]
Oh, they're already merged Haha. I assigned you to let you know. When you come back, use the build.gradle in the root, and it builds the two projects at once.
