### ISSUE TITLE
Fix or remove TIFF image support (kind of)

### ISSUE THREAD

**Issue by zgoethel12** [team-jgloom/jgloom#39]
In the current state of our project, the texture loader supports any image format as long as Java supports it or the proper plugin is installed.  I think that we should remove the TIFF plugin, especially because my Gradle configuration is not behaving correctly, and add into the documentation that any image format is supported as long as the proper plugin is installed.

**Comment by ecumene-software** [comment]
TIFF is a pretty useful format, and the whole point of the library is to support as any formats as possible. I'm sure the gradle issue is fixable! What's wrong?

**Comment by zgoethel12** [comment]
Importing into NetBeans works fine.  YAY ECLIPSE! :D
