### ISSUE TITLE
Using class.getResource in tests

### ISSUE THREAD

**Issue by ecumene-software** [team-jgloom/jgloom#42]
We should have some sort of universal method of changing a URL to Resource interface:
```
Resource myResource;
URL myURL = new URL("path/to/file.f");
myResource = ResourceFactory.fromClasspath(myURL);
myResource = ResourceFactory.fromClass(getClass(), myURL); // Uses class.getResource
```
Class resources usually look right next to the class, or in the same dir as the class. So in the resources folder here'd how those structures would load correctly for both:
```
resources/
 - file.f // Loads correctly with classpath loader
 - jgloom/my/package/whateves/file.f // Loads correctly with class resource loader
```

**Comment by zgoethel12** [comment]
Sorry if my code has been lacking, I get next to no sleep these days.

**Comment by ecumene-software** [comment]
Hehe I know that feel. Everything is fixable though! I'll make a commit later with the new ResourceFactory?

**Comment by zgoethel12** [comment]
Go ahead.  By the way, Gradle has completely stopped working with my Eclipse installation.  I create a project and a project folder is created, but an error occurs somewhere along the way and it never appears in the workspace.

**Comment by ecumene-software** [comment]
Are you importing the /build.gradle and not the child projects? Also maybe remove the .classpath and .project files to get a clean project. I forgot to commit the settings.gradle, which I'll do once I make the new branch

**Comment by ecumene-software** [comment]
Okay! New branch is made, try importing the gradle in the root of the project and the new settings.gradle  should build the child projects and all.

If that doesn't work try using PowerShell on windows and using the gradle command-line, it's very reliable. Good luck, and I might have a bit of delay because I'll be building a trampoline today.

**Comment by zgoethel12** [comment]
I just had to delete and recreate my workspace/settings (It's sad, I had Eclipse so personalized... at least it gave me a chance to update to Neon)

**Comment by ecumene-software** [comment]
I looked over the code a bit, and I quite like the interfaces you've made already! Adding a ResourceFactory could help pull the code together into one class, but this interface direction adds a whole new world of typing to the loading that makes for the file sources to be much more customizable. Nice work! I'll make a commit removing the `@FunctionalInterface` (they don't have abstract functions to begin with) and `public` (static interface functions are inherently public regardless).
