### ISSUE TITLE
Moving LWJGL from JGLOOm core

### ISSUE THREAD

**Issue by ecumene-software** [team-jgloom/jgloom#44]
We should move the JGLOOm lwjgl code to a different folder, so we can easily abstract out the code making it easier to develop the core library separate from LWJGL.   
New Structure:
```
build.gradle
jgloom/build.gradle
jgloom-lwjgl/build.gradle
jgloom-io/build.gradle
```
```
core gradle dependencies: none, only defines maven repos and target source/compile versions
jgloom dependencies: apache commons, joml
jgloom-lwjgl dependencies: lwjgl, lwjgl natives
jgloom-io dependencies: TIFF library, other file loading libs ... 
```

**Comment by zgoethel12** [comment]
I'll do this this evening or tomorrow and let you know about any issues.  Gradle integration with Eclipse Neon is actually broken (other people have issues with it), so I might need to transition to IDEA

**Comment by zgoethel12** [comment]
This won't work, all of the interfaces have identifiers which reference LWJGL.  I'll move what I can for now, and link the commits to this issue.

**Comment by ecumene-software** [comment]
Closing once #35 is complete

**Comment by ecumene-software** [comment]
BAM! #35 is complete!
