### ISSUE TITLE
Enumorators issue

### ISSUE THREAD

**Issue by ecumene-software** [team-jgloom/jgloom#45]
There's a pretty big issue I forgot about in the JGLOOm-IO project, how do we cross the barrier between libraries enumorator wise, I was thinking about something like this (and it's all I have to far + it's implemented right now)
Take for example the TextureLoader
```
public class TextureLoader {

    public static int E_11RGBA8; // E stands out when looking for fields in reflection
    public static int E_11RGB8; // 11 is the version class it comes from
    public static int E_11RGBA;
    public static int E_11RGB;
    public static int E_11FLOAT;
    public static int E_11TEXTURE_2D;

...
// In use:
texture.image2D(target, 0, callback.hasAlpha ? RGBA8 : RGB8, callback.width, callback.height, 0, callback.hasAlpha ? RGBA : RGB, FLOAT, data);
```

Then we have a class per-library like this:
```
public class LWJGLEnums {

...

public void setEnums(Class clazz){
    // Uses reflection to find enums with E_[version][enum] and sets them to the correct number
    // Using -1 to describe unusable enums between libraries (we can check between the versions)
```

This allows us to support specific enums from any library while also changing them dynamically per library also!

**Comment by ecumene-software** [comment]
The `jgloom.io.images.TextureLoader` is currently broken because of this

**Comment by zgoethel12** [comment]
I recommended this a long time ago

**Comment by ecumene-software** [comment]
Yeah I seen that, but that was a sort of central enum repository per-version like GL11. This is mainly extending off of that so we can have loader-specific enums, and they're set using reflection

**Comment by ecumene-software** [comment]
#35
