### ISSUE TITLE
Creating a custom bufferutils

### ISSUE THREAD

**Issue by ecumene-software** [team-jgloom/jgloom#46]
We need a buffer utils class pronto, that works without LWJGL. It needs to be able to:

- [x] Create any [Primitive]Buffer
- [x] Create any Construct any buffer from a given array of primitives (int[], float[])
- [x] Be able to decode buffers back to arrays (int[], float[])
- [x] Be in the `jgloom.utils` package

Without this the library doesn't function so it's technically a bug that we don't have one so far!

**Comment by ecumene-software** [comment]
The `jgloom.io.images.ImageDecoder` is currently broken because of this

**Comment by zgoethel12** [comment]
I have a to-do comment with this exact thing!  I'll get on it.

**Comment by zgoethel12** [comment]
I tested the new `BufferUtils` and, surprise, it works fine.  I'll add the other requested functionality soon.

**Comment by zgoethel12** [comment]
I can't really do much testing until the project successfully builds, so I'm going to close this issue since I have satisfied all of the requirements.  If it doesn't work or you want to add more functionality, we can reopen the issue.

**Comment by ecumene-software** [comment]
Holy shit that was quick. Nice job!
