### ISSUE TITLE
Seriously, who added the settings.gradle to the .gitignore?

### ISSUE THREAD

**Issue by ecumene-software** [team-jgloom/jgloom#47]
Here's the git log containing any changes referencing the keyword `settings.gradle`
```
commit f17028a22c818647889a56d794e7449c3d01eff9
Author: Mitchell Hynes <mitchell.hynes@ecumene.xyz>
Date:   Mon Jul 11 17:47:24 2016 -0230

    Uh, whoops?

commit b8be3586122235bd1c16feb06451b62c63140aa6
Author: Zach Goethel <zgoethel12@gmail.com>
Date:   Thu Jul 7 19:57:10 2016 -0500

    Reapplied changes by @ecumene-software

commit ad2730942dbc73dab1b70a37e3bfe363cad821e5
Author: Zach Goethel <zgoethel12@gmail.com>
Date:   Sat Jun 18 13:35:27 2016 -0500

    Quick, get the .gitignore up there!

commit 00d8258318ea68267d24e300bd8c8ac29b7c6136
Author: Zach Goethel <zgoethel12@gmail.com>
Date:   Tue May 10 16:26:48 2016 -0500

    Updated gitignore for Eclipse users.
```

**Comment by zgoethel12** [comment]
Did it get added again?

**Comment by ecumene-software** [comment]
Nope, still gone, but I wonder where it came from.

**Comment by zgoethel12** [comment]
I'm reading through commits - how long has it been like this?  At the very beginning it was there, but I was pretty sure it was removed since then.

**Comment by ecumene-software** [comment]
I copied the whole gitignore to a game I was working on a while back, and It's not in that one

**Comment by zgoethel12** [comment]
I was definitely the culprit...?  I added it a while back because the file didn't exist when I created my Eclipse project so I didn't want to push it.

**Comment by ecumene-software** [comment]
Case closed

**Comment by zgoethel12** [comment]
Every commit after kept it in, browsing the repo at each stage showed it ignored.  Yay, me!
