### ISSUE TITLE
Deploy to Maven Central

### ISSUE THREAD

**Issue by zgoethel12** [team-jgloom/jgloom#52]
I recently deployed my own project (`net.jibini:swiss-gl` version `1.0.0-SNAPSHOT`) to Maven snapshots.  I would like to deploy v1.0.0 of JGLOOm to Central and our current state as v1.1.0-SNAPSHOT (nightly build)

**Comment by ecumene-software** [comment]
Sure thing, but there's going to be a lot of changes before we finish it, so it's technically hardly out of 1.0.0 xD

**Comment by zgoethel12** [comment]
Do you have a JIRA account?  If so, please provide your username.  If not, please create one so I can grant you access to the Maven repository entry.

**Comment by zgoethel12** [comment]
Version `1.1.0-SNAPSHOT` has been deployed to the Sonatype snapshot repository with the group ID `com.jgloom` (`jgloom` is an invalid group ID) and artifact ID `jgloom`.  Soon I will deploy release `1.0.0` to Maven Central.  I will email you contents of a file called `gradle.properties` which is required to deploy (it contains passwords).  I still need your JIRA username.

**Comment by zgoethel12** [comment]
I sent the email containing setup information for deployment.  If you do not want to do anything with deployment or the setup, you can just leave Maven deployment to me.

**Comment by ecumene-software** [comment]
Im interested in maven so I might dabble down the line. I have a JIRA SSH key, but you can upload it for now!!

**Comment by zgoethel12** [comment]
I have "deployed" `1.0.0` (basically built and uploaded the `master` branch), and am waiting for staging to be enabled by an admin.

**Comment by zgoethel12** [comment]
Some issues have become apparent with sub-project deployment.  I am renaming `jgloom` to `jgloom-core` as part of the transition.

**Comment by ecumene-software** [comment]
I was planning to rename it to core in the future, thanks!

**Comment by zgoethel12** [comment]
How attached to Gradle are you?  I have (jibini-media/swiss-gl)[https://github.com/jibini-media/swiss-gl] nearly flawlessly set up with Maven, separated core and LWJGL artifacts

**Comment by zgoethel12** [comment]
I'm also asking because Gradle integration with Eclipse is completely broken (can't even create projects) and has issues in NetBeans (doesn't recognize classes from plugins).  Maven works great for me in Eclipse, and it works better for deployment.

**Comment by ecumene-software** [comment]
I'm somewhat attached, I just hate XML. I'd love to switch to maven once #49, #51, #48, #35, and #31 are complete. For now this is on the back burner. I'm going to see if I can blast through all those issues in the next few days. I've been offline for a bit since there's some events going on here, but I'm free to contribute now!

**Comment by ecumene-software** [comment]
It seems the issue you're having with gradle can be fixed by adding `include "jgloom-core" ` to `settings.gradle` and removing `include "jgloom"`

I'll do that now! The commit will be in `feat/meshes`

**Comment by ecumene-software** [comment]
I looked into it and I see no reason not to implement maven as the primary build platform, but I believe we should keep the `jgloom-core`, `jgloom-lwjgl`, and `jgloom-io` separate. (Or merge jgloom-io and jgloom in the future/soon)

**Comment by zgoethel12** [comment]
I am much better with Maven deployment with Maven, I'll do it this afternoon

**Comment by zgoethel12** [comment]
As of 4:00 Central, JGLOOm version `1.1.0-SNAPSHOT` is available for Maven-esque use!  I will not deploy version `1.0.0`, but when `1.1.0` is complete it will be synced to the Maven Central repository.

**Comment by zgoethel12** [comment]
Once I am granted access, I will change the group ID from `com.jgloom` to `org.jgloom`, the artifact IDs are `jgloom-core`, `jgloom-io`, and `jgloom-lwjgl`

**Comment by zgoethel12** [comment]
Just a note, `jgloom-tests` and the merged form of `jgloom-core` have been deployed.  `jgloom-io` still exists as an artifact on the internets, but will no longer be updated and will not be released with version `1.1.0`

**Comment by zgoethel12** [comment]
Here's a list of all artifacts under `com.jgloom`: https://oss.sonatype.org/#nexus-search;quick~com.jgloom

**Comment by ecumene-software** [comment]
Nice work!
