### ISSUE TITLE
JGLOOm.com or JGLOOm.org?

### ISSUE THREAD

**Issue by ecumene-software** [team-jgloom/jgloom#54]
I quite like both, but domain names are expensive! Discuss which is better? They're both 14$

**Comment by zgoethel12** [comment]
Opened a ticket for org.jgloom: [Issue OSSRH-23743](https://issues.sonatype.org/browse/OSSRH-23743)

**Comment by zgoethel12** [comment]
We're going with `org.jgloom` and therefore `jgloom.org`, I'm closing this issue.

**Comment by ecumene-software** [comment]
Okay, I'll buy the domain!!
