### ISSUE TITLE
Moving code to org.jgloom

### ISSUE THREAD

**Issue by ecumene-software** [team-jgloom/jgloom#55]
I'm going to move everything to org.jgloom shortly, I bought http://www.jgloom.org.

**Comment by zgoethel12** [comment]
I'll change the artifact IDs once Sonatype clears me for `org.jgloom`

**Comment by zgoethel12** [comment]
I have been granted access to `org.jgloom` - https://oss.sonatype.org/#nexus-search;quick~org.jgloom

**Comment by zgoethel12** [comment]
I can easily refactor the code.  If you assign me, I'll go ahead and do that.

**Comment by zgoethel12** [comment]
All code has been refactored, group IDs have been set to `org.jgloom`, and the new artifacts have been deployed.  I'll close this.
