### ISSUE TITLE
Merge between JGLOOm-IO and JGLOOm

### ISSUE THREAD

**Issue by ecumene-software** [team-jgloom/jgloom#56]
As I love the whole, "People can create their own alternative file loaders idea", I believe JGLOOm-IO and JGLOOm belong in the same project, because LWJGL, JOGL, and WebGL4J implementations will rely on the whole JGLOOm-IO model, which is proprietary and volatile if we leave it like this.

Moving `jgloom-io/.../jgloom.io` to `jgloom-core/.../jgloom.io`and `jgloom-io/.../tests/jgloom.io` to `jgloom-core/.../tests/jgloom.io` should have no issues code-base wise. 

@zgoethel12 How hard would it be to merge the two maven wise?

**Comment by ecumene-software** [comment]
Honestly I'm just worried about users seeing `jgloom-core` `jgloom-io` and `jgloom-[library]` and getting confused on which to download, which the answer would always be "The first two".

**Comment by zgoethel12** [comment]
Merging Maven-wise would be easy, should I do it?

**Comment by ecumene-software** [comment]
Yeah, I'll make a commit merging the two folders and later you make one editing the poms? I'll merge the dependencies though, that's easy

**Comment by ecumene-software** [comment]
BAM done did it, I'll move the dependencies now too

**Comment by zgoethel12** [comment]
Don't forget the properties in the poms, otherwise ERRORS WILL OCCUR! 😮

**Comment by zgoethel12** [comment]
And also don't forget to remove the module from the master pom

**Comment by ecumene-software** [comment]
Ugh, I give up, `mvn package` doesn't work. Save me maven guru!

**Comment by zgoethel12** [comment]
Have you installed Maven binaries and added them to your PATH variable (Windows)?

**Comment by ecumene-software** [comment]
The maven debian package is installed for me, and mvn works fine. But the `compile` and `package` tasks result in error logs, `jgloom-core` and `jgloom-lwjgl` now depend on each other, which causes a sort of cyclic overflow? I'm sure there's plenty of projects that depend on each other (but one is scoped for tests of course) online we can copy from!

**Comment by ecumene-software** [comment]
Oh, yeah. Here's the error log:
```
[ERROR] The projects in the reactor contain a cyclic reference: Edge between 'Vertex{label='com.jgloom:jgloom-core:1.1.0-SNAPSHOT'}' and 'Vertex{label='com.jgloom:jgloom-lwjgl:1.1.0-SNAPSHOT'}' introduces to cycle in the graph com.jgloom:jgloom-lwjgl:1.1.0-SNAPSHOT --> com.jgloom:jgloom-core:1.1.0-SNAPSHOT --> com.jgloom:jgloom-lwjgl:1.1.0-SNAPSHOT -> [Help 1]
```

**Comment by zgoethel12** [comment]
Oh, yes, Core included LWJGL (test) and LWJGL includes Core... is a merge a good idea?

**Comment by ecumene-software** [comment]
Yes, of course! This maven issue is just a config error, I'll find some way to fix it.

**Comment by zgoethel12** [comment]
Most people have a third module to avoid cyclic dependencies, like we used to.  We should keep IO separate, maybe?  Also, delete the files that got UN-gitignored

**Comment by ecumene-software** [comment]
Wouldn't `jgloom-io`'s tests rely on `jgloom-lwjgl`, and `jgloom-lwjgl` require `jgloom-io` to compile? We'll have the same issue down the line. It worked before because we didn't have `jgloom-io` in `jgloom-lwjgl`

**Comment by ecumene-software** [comment]
Maybe a `jgloom-tests`?
@zgoethel12

**Comment by zgoethel12** [comment]
OOOOH I like that idea, I'll do that for you tomorrow

**Comment by zgoethel12** [comment]
Actually, just fixed the cyclic dependency!

**Comment by ecumene-software** [comment]
Is `jgloom-lwjgl` supposed to be merged with `jgloom-core`? Also `jgloom-io` is still there?

**Comment by zgoethel12** [comment]
`lwjgl` is not merged with `core`, and `io` still exists on Maven as an artifact because I can not delete artifacts once deployed.  I promise it won't be on the release.  `io`'s project is gone, though.

**Comment by ecumene-software** [comment]
Here's some stackoverflow articles on deleting maven artifacts:
http://stackoverflow.com/questions/3692681/remove-artifacts-from-nexus-repository
http://stackoverflow.com/questions/26395479/how-to-remove-delete-an-artefact-via-maven-in-a-remote-nexus-repo

Can't we delete it from the nexus and the project also?

Also, I was looking at the wrong branch xD I'll close this issue when the `org.jgloom` group is approved

**Comment by zgoethel12** [comment]
https://issues.sonatype.org/plugins/servlet/mobile#issue/OSSRH-23743 Deletion of artifacts is against their policy, but don't worry - release `1.1.0` will not have the "deleted" (merged) artifacts

**Comment by zgoethel12** [comment]
It was just approved

**Comment by zgoethel12** [comment]
Oh, and by the way - Since we changed group IDs, `jgloom-io` will not be deployed to `org.jgloom` (just `com.jgloom`)

**Comment by ecumene-software** [comment]
Oh, that should save some people the confusion, having all the old libs in `com.jgloom`.

**Comment by zgoethel12** [comment]
I can't tell if that's sarcasm, or you actually think it will help confusion... XD

**Comment by ecumene-software** [comment]
I'm not a very sarcastic person unless I'm irritated. That wasn't sarcasm though, it's very hard to mix the two up, and tutorials will have `org`
